openapi: 3.0.1
info:
  title: Assignment 4 Swager Doc
  description: |-
    A swagger doc for these three endpoints:
    `GET /v1/weather` —mocking GET /data/2.5/weather
    `GET /v1/hello`  —will greet you with some message
    `GET /v1/auth` -will authorize the user
  contact:
    email: kondamp@oregonstate.edu
  license:
    name: myLicense
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://3.91.132.65/v1
tags:
- name: Peeyusha
  description: Know more
paths:
  /weather:
    get:
      tags:
      - user
      summary: Know temperature of some place
      description: Fatch current Temperature by entering your API id and name of the
        city
      operationId: getWeather
      parameters:
      - name: Name
        in: query
        description: City name
        required: true
        schema:
          type: string
      - name: API Key
        in: query
        description: API key
        required: true
        schema:
          type: string
      - name: token
        in: query
        description: enter token
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: string
        400:
          description: Invalid API Key, please enter the correct one
          content: {}
  /hello:
    get:
      tags:
      - user
      summary: Greetings!
      operationId: get_hello
      responses:
        200:
          description: Hello! How are you?
          content: {}
        400:
          description: Bad request
          content: {}
  /auth:
    post:
      tags:
      - user
      summary: Get your token to login
      operationId: userlogin
      requestBody:
        description: Enter your username and password
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: Logged in Successfully
          content: {}
        400:
          description: Bad request
          content: {}
        401:
          description: You're not authorized to use the services
          content: {}
      x-codegen-request-body-name: Details
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          description: Get Token
      xml:
        name: User
